package com.levylin.study.model;

import com.levylin.study.model.base.BaseCategorySuper;

import java.util.Set;
import java.util.TreeSet;

/**
 * Generated by JFinal.
 */
public class CategorySuper extends BaseCategorySuper<CategorySuper> implements Comparable<CategorySuper> {
    private static final long serialVersionUID = 2494210815555635119L;
    public static final CategorySuper dao = new CategorySuper();

    private Set<CategorySub> _categorySubList;

    public Set<CategorySub> getCategorySubList() {
        if (_categorySubList == null) {
            _categorySubList = new TreeSet<CategorySub>(CategorySub.dao.find("select * from category_sub where pId = ?", getId()));
        }
        return _categorySubList;
    }

    @Override
    public int compareTo(CategorySuper o) {
        if (getOrder() >= o.getOrder())
            return 1;
        else
            return -1;
    }
}
