package com.levylin.study.model;

import com.levylin.study.model.base.BaseCategorySub;

/**
 * Generated by JFinal.
 */
public class CategorySub extends BaseCategorySub<CategorySub> implements Comparable<CategorySub> {
    public static final CategorySub dao = new CategorySub();
    private static final long serialVersionUID = 1250386224779039815L;

    private CategorySuper _categorySuper;

    public CategorySuper getPcategory() {
        if (_categorySuper == null) {
            _categorySuper = CategorySuper.dao.findById(getInt("pId"));
        }
        return _categorySuper;
    }

    @Override
    public int compareTo(CategorySub o) {
        if (getOrder() >= o.getOrder())
            return 1;
        else
            return -1;
    }
}
