package com.levylin.study.model;

import com.levylin.study.model.base.BaseComment;

/**
 * Generated by JFinal.
 */
public class Comment extends BaseComment<Comment> {
    private static final long serialVersionUID = -4876657238164120728L;
    public static final Comment dao = new Comment();
}
