package com.levylin.study.model;

import com.levylin.study.model.base.BaseMessage;

/**
 * Generated by JFinal.
 */
public class Message extends BaseMessage<Message> {
    private static final long serialVersionUID = -2887309994975572248L;
    public static final Message dao = new Message();
}
