package com.levylin.study.model;

import com.levylin.study.model.base.BaseProject;

/**
 * Generated by JFinal.
 */
public class Project extends BaseProject<Project> {
    private static final long serialVersionUID = 3406656546362803681L;
    public static final Project dao = new Project();

    private String _finishText;

    public String getFinishText() {
        if (null == _finishText) {
            if (getFinish()) {
                _finishText = "已结束";
            } else {
                _finishText = "正在继续创中...";
            }
        }
        return _finishText;
    }
}
