package com.levylin.study.model;

import com.levylin.study.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
public class User extends BaseUser<User> {
    private static final long serialVersionUID = -1537215759857249457L;
    public static final User dao = new User();
}
