package com.levylin.study.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setCreateDateTime(java.util.Date createDateTime) {
		set("createDateTime", createDateTime);
	}

	public java.util.Date getCreateDateTime() {
		return get("createDateTime");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setViewCount(java.lang.Integer viewCount) {
		set("viewCount", viewCount);
	}

	public java.lang.Integer getViewCount() {
		return get("viewCount");
	}

	public void setReplyCount(java.lang.Integer replyCount) {
		set("replyCount", replyCount);
	}

	public java.lang.Integer getReplyCount() {
		return get("replyCount");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCategorySubId(java.lang.Integer categorySubId) {
		set("categorySubId", categorySubId);
	}

	public java.lang.Integer getCategorySubId() {
		return get("categorySubId");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}

	public java.lang.String getTags() {
		return get("tags");
	}

	public void setProjectId(java.lang.Integer projectId) {
		set("projectId", projectId);
	}

	public java.lang.Integer getProjectId() {
		return get("projectId");
	}

	public void setFinish(java.lang.Boolean finish) {
		set("finish", finish);
	}

	public java.lang.Boolean getFinish() {
		return get("finish");
	}

}
